---
- name: Download Vagrant
  get_url: url={{ vagrant_download_url }}
           dest=/usr/local/src/vagrant_{{ vagrant_version }}_{{ vagrant_arch }}.deb

- name: Install Vagrant
  apt: deb=/usr/local/src/vagrant_{{ vagrant_version }}_{{ vagrant_arch }}.deb
       state=installed
